### ISSUE TITLE
PTT short on Baofeng UV-5R

### ISSUE THREAD

**Issue by yuvadm** [skuep/AIOC#14]
I'm connecting a fully built AIOC to a Baofeng UV-5R and upon full connection the PTT triggers on and does not release.

There are no shorts on either of the TRS connectors. This happens regardless of whether the AIOC is USB-powered or not.

Is this expected?

**Comment by yuvadm** [comment]
I got the 2.5 and 3.5 reversed :facepalm:

**Comment by skuep** [comment]
😁 Sorry to hear! I was already thinking about what you could check and measure. There is currently a GitHub issue on a Windows System that asserts the PTT directly after plugging in. But it looks like this is not related then 👍

**Comment by yuvadm** [comment]
@skuep is it possible to switch between the plugs in software?

**Comment by yuvadm** [comment]
@skuep sorry for the bump and reopening, any chance I can salvage the existing board with a custom firmware fix instead of de-soldering?

**Comment by skuep** [comment]
Sorry, did not see your question. No unfortunately not, since the contacts of the two connectors are very special (e.g. audio, ptt, digital).

But you can desolder the TRS connectors, by bending or pulling on the tabs with tweezers,  while desoldering. You would need however new TRS connectors

**Comment by yuvadm** [comment]
Got it, thanks!
