### ISSUE TITLE
Firmware build instructions

### ISSUE THREAD

**Issue by techfoamer** [skuep/AIOC#18]
Are there instructions for building the firmware and the packages required to do so?  I'm thinking of some software mods.

**Comment by skuep** [comment]
You can import the project into STM32CubeIDE and just build it. Should work that way!

Let me know if this works and maybe include some details or problems you encounter so I can add a section to the README file.

Thanks! 🙂

**Comment by techfoamer** [comment]
So, something like this?

git clone https://github.com/skuep/AIOC.git
cd AIOC
git submodule update

**Comment by skuep** [comment]
That should be it!

**Comment by techfoamer** [comment]
This worked for me:

git clone https://github.com/skuep/AIOC.git
cd AIOC
git submodule update --init

...needed the --init for git to grab the tinyusb sources.  Now I can build the project!!

**Comment by skuep** [comment]
Thanks! I will update the README later :-)

**Comment by ITCMD** [comment]
Trying to follow the instructions. I have STM32IDE finally installed, and when I go to import, I don't see the AIOC-fw as an option:

![image](https://github.com/skuep/AIOC/assets/32961763/d5dfecf0-e8f2-4619-935a-577ec557071e)

The AIOC-FW folder is there and populated with files, but not showing up in stm32ide.
