### ISSUE TITLE
suggestion for phono jack alternative

### ISSUE THREAD

**Issue by pen25** [skuep/AIOC#26]
was thinking a good option would be a k connector extension instead of phono jacks. amazon has a 2 meter cable for 12 bucks usd. B07SKKV4DM is the item number. im going to try using this when i get my board next week,

**Comment by skuep** [comment]
That's perfectly doable! If you prefer to have a short length of wire between the AIOC and your HT that's a good way to do it. You could even plug in the AIOC directly into your extension :-)
