### ISSUE TITLE
Parameter Exception after uploading BOM / CPL to jlcpcb.com

### ISSUE THREAD

**Issue by peddamat** [skuep/AIOC#27]
I followed the instructions to fab the boards on jlcpcb.com, but I'm getting stuck after uploading the BOM and CPL files.  

<img width="1439" alt="image" src="https://github.com/skuep/AIOC/assets/869300/82f71845-0e5b-49e6-bf12-3d8dfbd489e1">

**Comment by skuep** [comment]
Interesting! I have never seen this nor do I know what could have gone wrong. When exactly did this happen in the process and have you tried again?

**Comment by skuep** [comment]
I will close the issue for now. If anyone else has the same problem, feel free to open it again.
