### ISSUE TITLE
Mirrored Wiring Firmware Support?

### ISSUE THREAD

**Issue by ITCMD** [skuep/AIOC#31]
Since RFI is an issue with the cable going parallel to the antenna, would it be possible to support having one wired up in reverse?

![20230704_160107](https://github.com/skuep/AIOC/assets/32961763/6e7bcb68-c60c-4062-a2fb-02f41c3c383d)

**Comment by skuep** [comment]
Unfortunately not. It would require a new PCB layout, since some special pins can not be just swapped (e.g. analog in/out or ground pin)

**Comment by ITCMD** [comment]
Makes sense. Perhaps a reversed image would be helpful

**Comment by skuep** [comment]
I had a few thoughts about it and I don't think I can currently do it easily as it requires a lot of hardware changes and I don't have a lot of spare time at the moment. A solution however could be to use a K1 connector extension cord?

**Comment by ITCMD** [comment]
Good idea for a workaround, that would likely work. Perhaps something like this: https://www.ebay.com/itm/303896324294

**Comment by ITCMD** [comment]
Unless you have any other thoughts, I'll close this one out for now!
