### ISSUE TITLE
BOM and CPL error from JLCPCB

### ISSUE THREAD

**Issue by rxt1077** [skuep/AIOC#39]
After uploading the BOM and CPL files to JCPCB I receive the following error:

```
The below parts won't be assembled due to data missing.
H1,H2 designators don't exist in the BOM file.
J2,D3,D4,R17 designators don't exist in the CPL file.
```

I went ahead and had the boards made anyway as I didn't readily see those items on the schematic.
If this really is an error that people don't need to worry about, we might want to update README.md to mention it.

**Comment by rxt1077** [comment]
I can confirm that this doesn't affect the board. They seem to be working great!

**Comment by skuep** [comment]
Thanks for the confirmation! :-)
