### ISSUE TITLE
jlcpcb missing parts

### ISSUE THREAD

**Issue by alper061** [skuep/AIOC#41]
When i upload the production files to jlcpcb, i got this:
The below parts won't be assembled due to data missing.
H1.H2designators don't exist in the BOM file.
J2,D3,D4,R17 designators don't exist in the CPL file
Is this a bug or can be ignored?

**Comment by rxt1077** [comment]
When I built these last week I received the same error and things still worked fine. Here's the issue I opened and closed: #39

**Comment by skuep** [comment]
Yep, thanks! I should add a note to the README about this :-)
