### ISSUE TITLE
Level of effort for a TNC Modem?

### ISSUE THREAD

**Issue by jeffersonbenson** [skuep/AIOC#5]
Just curious how much effort is required to implement a TNC into the project? I'm not too familiar with them from a technical level, but I think it would be a real value add for radios like the (tr)uSDX or even encouraging more 2m/70cm digital traffic in my area 😁

**Comment by SpudGunMan** [comment]
Direwolf is a very powerful tnc this works with Direwolf question is will it pass full bandwidth Vara as well?

**Comment by jeffersonbenson** [comment]
That totally makes sense! So really so long as there's a software TNC one should be good to go (as I'm understanding it. Thanks!
