### ISSUE TITLE
Documentation: clarify firmware build instructions // upload binary under "release"

### ISSUE THREAD

**Issue by gonium** [skuep/AIOC#6]
Hi,

first of all: thanks for your work, this looks interesting and I ordered a set of assembled PCBs. Now I realize that I don't understand how the firmware is build. I expected a Makefile or something, but that is not the case. Can you provide additional documentation regarding the firmware build process? 

Additionally, can you upload a binary firmware image under "Releases"? This would make it easy to get started.

Thanks,
-Mathias

**Comment by skuep** [comment]
Hi, Thanks for the bump.
I want to make a first Release of the firmware via GitHub soon. Stay tuned!
If you want, you can use STM32CubeIDE (no charge and cross-platform) to import the project and start compiling. I do my best to keep the master branch always compilable.

**Comment by gonium** [comment]
Thanks, I will try the STM32CubeIDE. I wasn't aware of it.

**Comment by skuep** [comment]
I have added a first Release of the Firmware that you can find under the Releases of this projects.
Nothing too automated yet, but should get the job done for now.

**Comment by gonium** [comment]
Thanks!
