### ISSUE TITLE
Retevis RT73

### ISSUE THREAD

**Issue by dc7os** [skuep/AIOC#62]
Could i program the RT73 with a computer running Win 10/11?

73 de Karsten DC7OS

**Comment by skuep** [comment]
That's a good question! I am not quite familiar with this radio and it's hard for me to found out just from the search results. I think your best bet is to join the discord channel and ask there. There are a lot of experienced people in terms of HTs. Win10/11 shouldn't be a problem.

**Comment by dc7os** [comment]
Ich jann Dir sagen, es tut einwandfrei mit Win11 und dem RT73

24.03.2024 12:51:38 Simon Küppers ***@***.***>:
