### ISSUE TITLE
Increase overhang timer for Virtual-COS feature

### ISSUE THREAD

**Issue by G1LRO** [skuep/AIOC#67]
The virtual-COS function works but is a little 'twitchy', closing the COS line between words sometimes. This causes problems particularly with AllStarLink as it then changes mode after the first drop of the COS line and does not forward subsequent audio segments.

If this setting can be manipulated with registers, please provide information on how this is done, or if this requires a code change please add to the front of the queue as otherwise the ASL support is now working in the AIOC and will be a very popular application.

An overhang of say 1.5 seconds would be helpful, and if configurable then up to 3 seconds would be useful.

Many thanks

**Comment by G1LRO** [comment]
in the file settings.h there is this definition for the VCOS timeout, it looks like it's set to 200ms which is probably too short.

```/* Virtual COS timing control register */
#define SETTINGS_REG_VCOS_TIMCTRL                           0x94
#define SETTINGS_REG_VCOS_TIMCTRL_DEFAULT                   (SETTINGS_REG_VCOS_TIMCTRL_TIMEOUT_DFLT)
/* TIMEOUT: Timeout (trailing) time in milliseconds in 12.4 format  */
#define SETTINGS_REG_VCOS_TIMCTRL_TIMEOUT_DFLT              ((uint32_t) (200 << 4) << SETTINGS_REG_VCOS_TIMCTRL_TIMEOUT_OFFS)
#define SETTINGS_REG_VCOS_TIMCTRL_TIMEOUT_OFFS              0
#define SETTINGS_REG_VCOS_TIMCTRL_TIMEOUT_MASK              0x0000FFFFUL
```

please can someone look to add the extra line to the script shown in https://github.com/skuep/AIOC/issues/61#issuecomment-2041084242 to increase the VCOS timeout to 1500ms?
@skuep is this a quick one for you please?

**Comment by skuep** [comment]
I will have a quick go at it.
Can you try this and post the output?

````
import sys
import hid
from struct import Struct
from enum import IntEnum, IntFlag

class Register(IntEnum):
    MAGIC = 0x00
    USBID = 0x08
    AIOC_IOMUX0 = 0x24
    AIOC_IOMUX1 = 0x25
    CM108_IOMUX0 = 0x44
    CM108_IOMUX1 = 0x45
    CM108_IOMUX2 = 0x46
    CM108_IOMUX3 = 0x47
    SERIAL_CTRL = 0x60
    SERIAL_IOMUX0 = 0x64
    SERIAL_IOMUX1 = 0x65
    SERIAL_IOMUX2 = 0x66
    SERIAL_IOMUX3 = 0x67
    VPTT_LVLCTRL = 0x82
    VPTT_TIMCTRL = 0x84
    VCOS_LVLCTRL = 0x92
    VCOS_TIMCTRL = 0x94

    
class Command(IntFlag):
    DEFAULTS = 0x10
    RECALL = 0x40
    STORE = 0x80


def read(device, address):
    data = device.get_feature_report(int(address), 5)
    address, value = Struct('<BL').unpack(data)
    return value

def write(device, address, value):
    data = Struct('<BL').pack(address, value)
    device.send_feature_report(data)

# AIOC is searched for on the system using these values
aioc = hid.Device(vid=0x1209, pid=0x7388)

magic = Struct("<L").pack(read(aioc, Register.MAGIC))

if (magic != b'AIOC'):
    sys.exit(-1)

print(f'Manufacturer: {aioc.manufacturer}')
print(f'Product: {aioc.product}')
print(f'Serial No: {aioc.serial}')
print(f'Magic: {magic}')

if False:
    # Load the hardware defaults
    print(f'Loading Defaults...')
    write(aioc, 0, Command.DEFAULTS)

if False:
    # Set USB VID and PID (use with caution. Will need changes above to be able to re-configure the AIOC)
    vid = 0x1209 # Set VID here
    pid = 0x7388 # Set PID here
    write(aioc, Register.USBID, (vid << 0) | (pid << 16))
    print(f'Now USBID: {read(aioc, Register.USBID):08x}')

if True:
    # Set VCOS trail time
    vcos_trail_ms = 1500
    write(aioc, Register.VCOS_TIMCTRL, (vcos_trail_ms << 4))
    print(f'Now TIMCTRL: {read(aioc, Register.VCOS_TIMCTRL):08x}')

if True:
    # Store settings into flash
    print(f'Storing...')
    write(aioc, 0, Command.STORE)
````

**Comment by G1LRO** [comment]
Thanks Simon, I'm AFK for a week, but have asked Murf to take a look.

**Comment by G1LRO** [comment]
Hi Simon I've run the script and have this output:

```admin@raspberrypi:~ $ sudo python aioc.py
Manufacturer: AIOC
Product: All-In-One-Cable
Serial No: 218077db
Magic: b'AIOC'
Loading Defaults...
Now USBID: 000c0d8c
Now VCOS_TIMCTRL: 00005dc0
Storing...
```
so now i'm going to build an ASL node and give it a go :)

**Comment by G1LRO** [comment]
Hi Simon, I can confirm this has implemented the extended hang time on the COS, the behavior is much better now on ASL.

I'll add the fully documented ASL implementation to #61 before closing that.

**Comment by skuep** [comment]
> Hi Simon, I can confirm this has implemented the extended hang time on the COS, the behavior is much better now on ASL.
> 
> I'll add the fully documented ASL implementation to #61 before closing that.

Nice! That sounds really good. What do you suggest as a sane default for the COS signal that won't drive anyone from the ASL team crazy? Since I have no stakes in ASL, I cannot answer this myself.
