### ISSUE TITLE
Fatal error while building on cubeIDE

### ISSUE THREAD

**Issue by PhipsmonET** [skuep/AIOC#69]
Hi guys i'm having some difficulties to build your code in CubeIDE. 
Basically whatever i do it gives me back "../Src/usb.c:4:10: fatal error: tusb.h: No such file or directory" while building, it almost seems like the makefile doesn't know where to find the src of tinyusb. 

Do you guys by any chanche still have a copy of the cubeIDE project folder?

**Comment by skuep** [comment]
See https://github.com/skuep/AIOC/issues/49

**Comment by PhipsmonET** [comment]
thanks, solved!
