### ISSUE TITLE
Error while debugging on a nucleo f302

### ISSUE THREAD

**Issue by PhipsmonET** [skuep/AIOC#70]
Hey, i'm trying to implement this on a nucleo f302r8 board but I'm facing some issue while launching the debug in CubeIDE. 
Basically after a succesful build I get this error in debug:

Error in final launch sequence:

Failed to execute MI command:
load C:\\Users\\pit\\Desktop\\stm32\\aioc-fw\\Debug\\aioc-fw.elf 

Error message from debugger back end:
Load failed
Failed to execute MI command:
load C:\\Users\\pit\\Desktop\\stm32\\aioc-fw\\Debug\\aioc-fw.elf 

Error message from debugger back end:
Load failed
Failed to execute MI command:
load C:\\Users\\pit\\Desktop\\stm32\\aioc-fw\\Debug\\aioc-fw.elf 

Error message from debugger back end:
Load failed
Load failed

Is this an already known issue? 
Thanks!

**Comment by PhipsmonET** [comment]
I've just noticed that the bin size of my release bild is way bigger than the build that Skuep has given us, i'm sure im missing somenthing. 

P.S my bin file is 125Kb, way bigger than the flash size of the f302

**Comment by skuep** [comment]
I am not exactly sure.. my files are a Release build... What linker script do you use?

**Comment by PhipsmonET** [comment]
Ah thanks!, that might be the problem! I was indeed using the 302cb linker so no wonder it didn'work. 
I'll try to build with the 302r8 script and get back to you as soon as possible.

**Comment by skuep** [comment]
I am going to close this issue, feel free to reopen if you have problems.
