### ISSUE TITLE
SSTV Support

### ISSUE THREAD

**Issue by KDMcMullan** [skuep/AIOC#74]
Is there any potential for the AIOC to be a MODEM for SSTV?

**Comment by skuep** [comment]
The AIOC itself can be used to interface with SSTV software that will then decode the signal. But the AIOC cannot decode those signal on its own.

**Comment by skuep** [comment]
I am going to close this issue due to inactivity. Feel free to reopen if required.

**Comment by KDMcMullan** [comment]
Thank you. I recently got an HF set and realised that there's very little SSTV on 2m anyway. I sincerely hope that little interfaces like this cause a resurgeance on 2m and that the band picks up again with your help. Thanks again.
