### ISSUE TITLE
PCB 1.2 Issues with k5prog

### ISSUE THREAD

**Issue by Radio-X24** [skuep/AIOC#97]
k5prog v0.01.27
Windows 10 Pro

aioc-fw-1.2.0.bin - Board 1.2 - error: k5_write_flash() At 20%
aioc-fw-1.3.0-rc.1.bin - Board 1.2 - error: k5_write_flash() [0] At 
aioc-fw-1.3.0-rc.2.bin - Board 1.2 - error: k5_write_flash() [0] At 5%

Attempting to flash firmware with k5prog v0.01.27 results in an error, however browser based flashing works fine

Have not yet tested with any other versions of k5prog.

I will update this once ive done some more tests.

**Comment by Radio-X24** [comment]
I will close for now, i think this is an issue on my end and not the fault of firmware 

i will still check this out further but closed.

**Comment by Radio-X24** [comment]
Totally all my fault, 

Issues cause having '' listen to this device '' enabled in windows sound settings.

**Comment by skuep** [comment]
Regarding hardware please 1.2 please note that the firmware is not yet complete. See the corresponding pull request
https://github.com/skuep/AIOC/pull/93#issuecomment-2506568260
